require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3.1
  NewCops: enable
  Exclude:
    - 'log/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - '.bundle/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'coverage-rspec/**/*'
    - 'coverage-jest/**/*'
    - 'Dockerfile.ruby'
    - 'Dockerfile.nodejs'
# Ruby 3.3 call to `it` without arguments in block with no ordinary parameters are deprecated.
# In Ruby 3.4, it will refer to the first block parameter.
# This cop will have to be updated to `EnforcedStyle: block_parameters`
# https://github.com/rubocop/rubocop/issues/12571
Naming/BlockForwarding:
  EnforcedStyle: explicit

# RSpec
RSpec/VariableName:
  EnforcedStyle: snake_case
RSpec/MultipleMemoizedHelpers:
  Max: 15

# Metrics
Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 300
Metrics/ModuleLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^(\s*#)'] # ignore commented out lines
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

# Style
Style/RaiseArgs:
  EnforcedStyle: compact
