services:
  ruby-test:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    image: coding-challenges/ruby:latest
    entrypoint: ./docker-entrypoint-ruby.sh
    command: guard --no-interactions
    volumes:
      - bundle_cache:/bundle
      - ./coverage:/coding-challenges/coverage
    networks:
      - coding_challenges_network
    develop:
      watch:
        - action: sync
          path: .
          target: /coding-challenges
        - action: rebuild
          path: Gemfile

  typescript-test:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    image: coding-challenges/typescript:latest
    entrypoint: ./docker-entrypoint-nodejs.sh
    command: npm run test:watch
    volumes:
      - node_modules_cache:/coding-challenges/node_modules
    networks:
      - coding_challenges_network
    develop:
      watch:
        - action: sync
          path: .
          target: /coding-challenges
        - action: rebuild
          path: package.json

volumes:
  bundle_cache:
  node_modules_cache:

networks:
  coding_challenges_network:
