services:
  guard:
    build:
      context: .
    command: guard --no-interactions
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - bundle_cache:/bundle
    networks:
      - coding_challenges_network
    develop:
      watch:
        - action: sync
          path: .
          target: /coding-challenges
        - action: rebuild
          path: Gemfile

  test:
    build:
      context: .
    command: rspec
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/coding-challenges
      - bundle_cache:/bundle
    networks:
      - coding_challenges_network

volumes:
  bundle_cache:

networks:
  coding_challenges_network:
